# File: netlify.toml

[build]
command = "next build"
publish = ".next"

# This is the proxy rule for Netlify's server.
# It tells Netlify: "Any request to /api/* should be sent to the destination URL."
[[redirects]]
from = "/api/*"
to = "https://archlinux.tail9023a4.ts.net/:splat"
status = 200 # This makes it a rewrite (proxy), not a 301/302 redirect.