# File: netlify.toml

# [build] and [plugins] are for when Netlify deploys your site in the cloud.
[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# [[redirects]] is for when your site is LIVE on Netlify's servers.
# It tells Netlify's network how to proxy requests.
[[redirects]]
  from = "/api/*"
  to = "https://archlinux.tail9023a4.ts.net/:splat"
  status = 200

# [dev] is for when you run your site LOCALLY using `netlify dev`.
# This is the modern way to replace the `next.config.js` rewrites.
[dev]
  # This tells the local Netlify server to proxy /api/* requests.
  [[redirects]]
    from = "/api/*"
    to = "https://archlinux.tail9023a4.ts.net/:splat"
    status = 200